### ISSUE TITLE
Kicad Projects now have the `*.kicad_pro` extension, and schematics use `*.kicad_sch`

### ISSUE THREAD

**Issue by xobs** [ryanfobel/kicad-helpers#25]
As of Kicad6, it looks like the file extension has changed:

```
[18:37:47] E:/Code/Farpatch> dir

    Directory: E:\Code\Farpatch

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          19/03/2022    18:38                Farpatch-backups
d----          19/03/2022    15:54                Farpatch.footprints.pretty
-a---          19/03/2022    18:38         718425 _autosave-Farpatch.kicad_pcb
-a---          19/03/2022    18:22         152572 _autosave-Farpatch.kicad_sch
-a---          19/03/2022    18:05            246 .gitattributes
-a---          19/03/2022    18:05             32 .gitignore
-a---          19/03/2022    18:22             47 #auto_saved_files#
-a---          19/03/2022    17:55         148092 02-Wifi.kicad_sch
-a---          19/03/2022    18:27         718425 Farpatch.kicad_pcb
-a---          19/03/2022    18:27           1143 Farpatch.kicad_prl
-a---          19/03/2022    17:43          11256 Farpatch.kicad_pro
-a---          19/03/2022    17:55         152572 Farpatch.kicad_sch
-a---          19/03/2022    12:50         133670 Farpatch.kicad_sym
-a---          19/03/2022    17:44        3138339 fp-info-cache
-a---          19/03/2022    09:35            127 fp-lib-table
-a---          19/03/2022    09:34            120 sym-lib-table

[18:40:23] E:/Code/Farpatch>
```

As a result, `kh_update` no longer works, because it assumes projects end in `*.pro`:

```
18:37:36] E:/Code/Farpatch> C:\Users\sean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\kh_update
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\kh_update.exe\__main__.py", line 7, in <module>
  File "C:\Users\sean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fastcore\script.py", line 112, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "C:\Users\sean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kicad_helpers\actions.py", line 177, in update_project
    update_templates(v=v, overwrite=overwrite, root=root)
  File "C:\Users\sean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kicad_helpers\actions.py", line 32, in update_templates
    metadata = get_project_metadata(root)
  File "C:\Users\sean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kicad_helpers\utilities.py", line 87, in get_project_metadata
    metadata["project_name"]=get_project_name(root)
  File "C:\Users\sean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kicad_helpers\utilities.py", line 65, in get_project_name
    return os.path.splitext(os.path.split(glob.glob(os.path.join(root, "*.pro"))[0])[1])[0]
IndexError: list index out of range
[18:37:47] E:/Code/Farpatch>
```

**Comment by xobs** [comment]
Also, schematic files are now called `*.kicad_sch` instead of `*.sch`
